version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysqlservice
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
    volumes:
      - ~/.data/db:/var/lib/mysql
